---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

clone:
  git:
    image: xoxys/plugin-git:devel

steps:
  markdownlint:
    image: quay.io/thegeeklab/markdownlint-cli
    commands:
      - markdownlint 'README.md' 'CONTRIBUTING.md'

  spellcheck:
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - cat .dictionary
      - spellchecker --files 'README.md' 'CONTRIBUTING.md' -d .dictionary -p spell indefinite-article syntax-urls
    environment:
      FORCE_COLOR: "true"
      NPM_CONFIG_LOGLEVEL: "error"
